---
title: "enade-ufcg"
author: "Hector Medeiros - Helder Machado de Lima"
date: "03/05/2019"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(hrbrthemes)
library(plotly)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

theme_set(theme_ipsum())

respostas_ufcg = read_csv(here::here("data/enade-ufcg-2017.csv"),
                     col_types = "cccdccdddc")

respostas_enade = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

respostas_ufcg$NOME_CURSO <- respostas_ufcg$NOME_CURSO %>%
    str_replace("Engenharia \\(1106561\\)", "Engenharia de Biotecnologia e Bioprocessos \\(1106561\\)") %>%
    str_replace("Engenharia \\(118562\\)", "Engenharia de Petróleo \\(118562\\)") %>%
    str_replace("Engenharia \\(13445\\)", "Engenharia de Materiais \\(13445\\)") %>%
    str_replace("Engenharia \\(13444\\)", "Engenharia de Minas \\(13444\\)")


respostas_ufcg <- respostas_ufcg %>% separate(NOME_CURSO, c("Curso", "Tipo", "e-MEC"), "\\ \\(")
respostas_ufcg <- respostas_ufcg %>%
    mutate(`e-MEC` = if_else(is.na(`e-MEC`), Tipo, `e-MEC`)) %>%
    mutate(`Tipo` = if_else(`e-MEC` == Tipo, "Bacharelado", Tipo))

respostas_ufcg$Tipo <- respostas_ufcg$Tipo %>% str_replace("\\)", "")
respostas_ufcg$`e-MEC` <- respostas_ufcg$`e-MEC` %>% str_replace("\\)", "")
```

### Visualização 1

```{r}
medias_ufcg = respostas_ufcg %>% 
    filter(categoria != "Outros") %>% 
    group_by(Curso,categoria) %>% 
    summarise(media = mean(media))

a <- respostas_ufcg %>%
    filter(categoria == "Infraestrutura") %>%
    ggplot(aes(x = media, y = reorder(Curso, media))) +
    geom_jitter(width = .1, alpha = .2) +
    geom_point(
        data = filter(medias_ufcg, categoria == "Infraestrutura"),
        color = "orange",
        shape = 15,
        size = 3
    )



ggplotly(a)
```

### Visualização 2

```{r}
medias_p <- respostas_ufcg %>%
    filter(categoria != "Outros") %>%
    group_by(categoria) %>%
    summarise(media = mean(media))

p <- respostas_ufcg %>%
    filter(categoria != "Outros") %>%
    ggplot(aes(x = reorder(categoria, media), y = media)) +
    geom_jitter(aes(text = paste("Curso:", Curso, "<br>Tema:", tema, "<br>Média:", round(media, 3))), width = .15, alpha = .4, color = 'deepskyblue1') +
    geom_boxplot(coef=100) +
    labs(title = "Avaliações do ENADE para os cursos da UFCG",
         x = "Categorias",
         y = "Avaliações do ENADE (1 a 6)")


ggplotly(p)
```

### Visualização 3

```{r}
q <-  respostas_ufcg %>%
    filter(categoria != "Outros") %>%
    ggplot(aes(x = media, y = reorder(categoria, media), color = Tipo)) +
    geom_jitter(aes(text = paste("Curso:", Curso, "<br>Tema:", tema, "<br>Média:", round(media, 3))), width = .1, alpha = .5) +
    labs(title = "Avaliações do ENADE para os cursos da UFCG",
         x = "Categorias",
         y = "Avaliações do ENADE (1 a 6)") 

ggplotly(q)
```

### Visualização 4

```{r}
dados = respostas_enade %>% na.omit() %>%  group_by(IES,tema) %>%
    filter(tema == "Oport. de extensão" | tema == "Iniciação científica" | tema == "Conteúdo útil p/ prática" | tema =="Formação cidadã e profissional"| tema =="Diversidade") %>%
    summarise(media_universidades = mean(media))

dados %>%  plot_ly(y = ~IES,x = ~media_universidades, type = "scatter", color = ~tema,
            text = ~paste('<br>IES: ', IES, '<br>Media: ', media_universidades)) %>% 
    layout(title = "Avaliação média das atividades extracurriculares ofertadas pelas Universidades Brasileiras",
           yaxis = list(title = "Universidade"),
           xaxis = list(title = "Media"))
```
